#!/bin/bash

dir=$(dirname $(readlink -f "$0"))

cd "$dir"

lspci -m | grep uPD720202 | while read device trailer; do
	if ! dmesg | grep "0000:$device" | tail -n 1 | grep -e "-110" > /dev/null; then
		continue # not affected, device got up normally
	fi

	bus=$( echo "$device" | cut -d : -f 1)
	dev=$( echo "$device" | cut -d : -f 2 | cut -d . -f 1)
	fun=$( echo "$device" | cut -d : -f 2 | cut -d . -f 2)

	./upd72020x-load -u -b 0x$bus -d 0x$dev -f 0x$fun -i ./K2026.mem

	sleep 1

	echo 1 > "/sys/bus/pci/devices/0000:$device/remove"
done

sleep 1

echo 1 > /sys/bus/pci/rescan

exit 0

